import { PKPass } from 'passkit-generator';
import type { CustomerCard, CustomerCardPassGenerator } from './customerCardService';
import { createCardIcon } from './cardIcon';

export interface ApplePassMaterial {
  readonly organizationName: string;
  readonly passTypeIdentifier: string;
  readonly signerCert: string;
  readonly signerKey: string;
  readonly signerKeyPassphrase?: string;
  readonly teamIdentifier: string;
  readonly wwdr: string;
}

export interface CertificateRepository {
  get(): Promise<ApplePassMaterial>;
}

export class ApplePassService implements CustomerCardPassGenerator {
  constructor(private readonly certificateRepository: CertificateRepository) {}

  async generate(card: CustomerCard): Promise<Buffer> {
    const material = await this.certificateRepository.get();
    const pass = new PKPass(
      {},
      {
        wwdr: material.wwdr,
        signerCert: material.signerCert,
        signerKey: material.signerKey,
        ...(material.signerKeyPassphrase && {
          signerKeyPassphrase: material.signerKeyPassphrase,
        }),
      },
      {
        formatVersion: 1,
        serialNumber: card.id,
        description: 'Demo customer card',
        organizationName: material.organizationName,
        passTypeIdentifier: material.passTypeIdentifier,
        teamIdentifier: material.teamIdentifier,
        logoText: 'Customer Card',
        backgroundColor: 'rgb(30, 64, 175)',
        foregroundColor: 'rgb(255, 255, 255)',
        labelColor: 'rgb(219, 234, 254)',
      }
    );

    pass.type = 'storeCard';
    pass.setBarcodes({
      message: card.id,
      format: 'PKBarcodeFormatQR',
      messageEncoding: 'utf-8',
      altText: card.id,
    });
    pass.primaryFields.push({ key: 'name', label: 'NAME', value: card.name });
    pass.secondaryFields.push({ key: 'cardId', label: 'CARD ID', value: card.id });
    pass.backFields.push({
      key: 'about',
      label: 'ABOUT',
      value: 'A non-production customer card generated by an AWS working probe.',
    });

    pass.addBuffer('icon.png', createCardIcon(29));
    pass.addBuffer('icon@2x.png', createCardIcon(58));
    return pass.getAsBuffer();
  }
}
